# Generated by Django 4.2.8 on 2023-12-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculteur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
