# Generated by Django 4.2.8 on 2023-12-17 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0002_alter_agriculteur_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParcelleAgricole',
            new_name='Parcelle',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='Agriculteur',
        ),
        migrations.AddField(
            model_name='exploitation',
            name='Agriculteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.agriculteur'),
        ),
        migrations.AddField(
            model_name='exploitation',
            name='beefriendly',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelle',
            name='Exploitation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carto.exploitation'),
            preserve_default=False,
        ),
    ]
