# Generated by Django 4.2.8 on 2023-12-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0004_alter_parcelle_exploitation_alter_parcelle_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelle',
            name='nom',
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
