# Generated by Django 4.2.8 on 2023-12-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_structure', models.CharField(max_length=100)),
                ('types', models.CharField(choices=[('individual', 'Exploitation individuelle'), ('collective', 'Exploitation collective')], max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exploitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('surface', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ParcelleAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('coordinates', models.JSONField()),
                ('Agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carto.agriculteur')),
            ],
        ),
    ]
